# Generated by Django 4.1 on 2022-09-05 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
