# Generated by Django 4.1 on 2022-09-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
