# Generated by Django 4.1 on 2022-09-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_rename_time_create_contact_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='create',
            new_name='created',
        ),
    ]
